# vim: set expandtab shiftwidth=4 softtabstop=4:
# Using this version string helps with some older docker-compose versions that
# we regularly encounter. It also ensures the 'extend' feature works.
version: "2.4"

volumes:
    fqdn:
    enrolldb:
    attestdb:
    kdc_primary:
    kdc_secondary:
    sherver:
    tpm_aclient:
    tpmsocket_aclient:
    tpm_kdc_primary:
    tpmsocket_kdc_primary:
    tpm_kdc_secondary:
    tpmsocket_kdc_secondary:
    tpm_workstation1:
    tpmsocket_workstation1:
    tpm_sherver:
    tpmsocket_sherver:

networks:
    emgmt_private:
        internal: true
    kdc_primary_private:
        internal: true
    kdc_secondary_private:
        internal: true
    hcpnetwork:
        # internal: true

services:

    common:
        image: ${HCP_IMAGE_caboodle}
        init: true
        volumes:
          - fqdn:/fqdn-bus:rw
          - ${HCP_TOP}/usecase:/usecase:ro
        environment:
          - HCP_LAUNCHER_TGTS=${HCP_LAUNCHER_TGTS:-}
          - HCP_NOTRACEFILE=1
          - VERBOSE=${VERBOSE:-0}

# Enrollment svc, mgmt interface
    emgmt:
        extends: common
        hostname: emgmt.hcphacking.xyz
        networks:
          - hcpnetwork
          - emgmt_private
        volumes:
          - enrolldb:/enrolldb:rw
          - ${HCP_TESTCREDS_ENROLLSIGNER}:/enrollsigner:ro
          - ${HCP_TESTCREDS_ENROLLCERTISSUER}:/enrollcertissuer:ro
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - ${HCP_TESTCREDS_ENROLLSERVER}:/enrollserver:ro
          - ${HCP_TOP}/vendors:/vendors:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/emgmt.json
#        ports:
#          - "8443:8443"
        healthcheck:
            test: /hcp/common/webapi.sh healthcheck
            timeout: 3s
            interval: 10s
    emgmt_pol:
        extends: common
        hostname: emgmt_pol.hcphacking.xyz
        networks:
          - emgmt_private
        environment:
          - HCP_CONFIG_FILE=/usecase/emgmt_pol.json
        healthcheck:
            test: /hcp/common/webapi.sh healthcheck
            timeout: 3s
            interval: 10s

# Enrollment svc, replication interface
    erepl:
        extends: common
        hostname: erepl.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes: # TODO: mount this at /enrolldb-ro? (For monolith...)
          - enrolldb:/enrolldb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/erepl.json
#        ports:
#          - "9418:9418"
        healthcheck:
            test: /hcp/enrollsvc/repl_healthcheck.sh
            timeout: 3s
            interval: 10s

# Attestation svc, replication client
    arepl:
        extends: common
        hostname: arepl.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - attestdb:/attestdb:rw
        environment:
          - HCP_CONFIG_FILE=/usecase/arepl.json
        healthcheck:
            test: test -f /attestdb/initialized && ! test -f /attestdb/hcp/transient-failure
            timeout: 3s
            interval: 10s

# Attestation svc, attestation interface
    ahcp:
        extends: common
        hostname: ahcp.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - attestdb:/attestdb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/ahcp.json
        healthcheck:
            test: /hcp/common/webapi.sh healthcheck
            timeout: 3s
            interval: 10s

# Orchestrator client (create and/or enroll TPMs). You'll typically want to
# pass "-c -e" to this to make it do something.
    orchestrator:
        extends: common
        hostname: orchestrator.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - tpm_aclient:/tpm_aclient
          - tpm_kdc_primary:/tpm_kdc_primary
          - tpm_kdc_secondary:/tpm_kdc_secondary
          - tpm_workstation1:/tpm_workstation1
          - tpm_sherver:/tpm_sherver
        environment:
          - HCP_CONFIG_FILE=/usecase/orchestrator.json

# Attestation client
    aclient:
        extends: common
        hostname: aclient.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - tpmsocket_aclient:/tpm_socket_aclient
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/aclient.json
    aclient_tpm:
        extends: common
        hostname: aclient_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_aclient:/tpm_aclient
          - tpmsocket_aclient:/tpm_socket_aclient
        environment:
          - HCP_CONFIG_FILE=/usecase/aclient_tpm.json
        healthcheck:
            test: /hcp/swtpmsvc/healthcheck.sh
            timeout: 3s
            interval: 10s

# Kerberos Domain Controller - Primary
    kdc_primary:
        extends: common
        hostname: kdc_primary.hcphacking.xyz
        volumes:
          - kdc_primary:/kdc_primary
          - tpmsocket_kdc_primary:/tpm_socket_kdc_primary
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        networks:
          - hcpnetwork
          - kdc_primary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_primary.json
        ports:
          - "9090:9090"
        healthcheck:
            test: /hcp/common/webapi.sh healthcheck
            timeout: 3s
            interval: 10s
    kdc_primary_tpm:
        extends: common
        hostname: kdc_primary_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_kdc_primary:/tpm_kdc_primary
          - tpmsocket_kdc_primary:/tpm_socket_kdc_primary
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_primary_tpm.json
        healthcheck:
            test: /hcp/swtpmsvc/healthcheck.sh
            timeout: 3s
            interval: 10s
    kdc_primary_pol:
        extends: common
        hostname: kdc_primary_pol.hcphacking.xyz
        networks:
          - kdc_primary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_primary_pol.json
        healthcheck:
            test: /hcp/common/webapi.sh healthcheck
            timeout: 3s
            interval: 10s

# Kerberos Domain Controller - Secondary
    kdc_secondary:
        extends: common
        hostname: kdc_secondary.hcphacking.xyz
        volumes:
          - kdc_secondary:/kdc_secondary
          - tpmsocket_kdc_secondary:/tpm_socket_kdc_secondary
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        networks:
          - hcpnetwork
          - kdc_secondary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_secondary.json
        healthcheck:
            test: /hcp/common/webapi.sh healthcheck
            timeout: 3s
            interval: 10s
    kdc_secondary_tpm:
        extends: common
        hostname: kdc_secondary_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_kdc_secondary:/tpm_kdc_secondary
          - tpmsocket_kdc_secondary:/tpm_socket_kdc_secondary
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_secondary_tpm.json
        healthcheck:
            test: /hcp/swtpmsvc/healthcheck.sh
            timeout: 3s
            interval: 10s
    kdc_secondary_pol:
        extends: common
        hostname: kdc_secondary_pol.hcphacking.xyz
        networks:
          - kdc_secondary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_secondary_pol.json
        healthcheck:
            test: /hcp/common/webapi.sh healthcheck
            timeout: 3s
            interval: 10s

# SSH host
    sherver:
        extends: common
        hostname: sherver.hcphacking.xyz
        volumes:
          - sherver:/sherver:rw
          - tpmsocket_sherver:/tpm_socket_sherver
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        networks:
          - hcpnetwork
        environment:
          - HCP_CONFIG_FILE=/usecase/sherver.json
        healthcheck:
            test: /hcp/sshsvc/healthcheck.sh
            timeout: 3s
            interval: 10s
    sherver_tpm:
        extends: common
        hostname: sherver_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_sherver:/tpm_sherver
          - tpmsocket_sherver:/tpm_socket_sherver
        environment:
          - HCP_CONFIG_FILE=/usecase/sherver_tpm.json
        healthcheck:
            test: /hcp/swtpmsvc/healthcheck.sh
            timeout: 3s
            interval: 10s

# 'workstation1' represents an architypal machine that is bootstrapped by the
# HCP infrastructure. It gets provisioned with host and user credentials, and
# can be used to interact with Kerberos and SSH services on the network in a
# SSO manner. It is used (non-interactively) for this purpose by the
# 'services_basic' test case.
    workstation1:
        extends: common
        hostname: workstation1.hcphacking.xyz
        environment:
          - HCP_CONFIG_FILE=/usecase/workstation1.json
          - HCP_NOTRACEFILE=1
        volumes:
          - ${HCP_TOP}/vendors:/vendors:ro
          - tpmsocket_workstation1:/tpm_socket_workstation1
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        networks:
          - hcpnetwork
        ports:
          - "3000:3000"
        healthcheck:
            test: /hcp/caboodle/networked_healthcheck.sh
            timeout: 3s
            interval: 10s
    workstation1_tpm:
        extends: common
        hostname: workstation1_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_workstation1:/tpm_workstation1
          - tpmsocket_workstation1:/tpm_socket_workstation1
        environment:
          - HCP_CONFIG_FILE=/usecase/workstation1_tpm.json
        healthcheck:
            test: /hcp/swtpmsvc/healthcheck.sh
            timeout: 3s
            interval: 10s

# 'monolith' exists to run all of the workloads that the targets above run in
# separate containers, but running them co-tenant within this single container
# rather than broken out. (HCP implements a "docker-compose" replacement called
# "monolith.py" that can be hooked into test scripts, and that causes it to
# invoke launcher.py directly rather than doing so via docker-compose commands
# into separate containers.)
    monolith:
        extends: common
        hostname: monolith.hcphacking.xyz
        environment:
          - HCP_IN_MONOLITH=1
          - HCP_CONFIG_FILE=/usecase/monolith.json
          - HCP_NOTRACEFILE=1
        volumes:
          - ${HCP_TOP}/vendors:/vendors:ro
          - ${HCP_TESTCREDS_ENROLLSIGNER}:/enrollsigner:ro
          - ${HCP_TESTCREDS_ENROLLCERTISSUER}:/enrollcertissuer:ro
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - ${HCP_TESTCREDS_ENROLLSERVER}:/enrollserver:ro
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
          - ${HCP_TOP}/tests:/tests:ro
        networks:
          - hcpnetwork
        ports:
          - "3001:3000"
        healthcheck:
            test: /bin/true
            timeout: 3s
            interval: 10s

# 'uml_runner' exists as a shim to run an arbitrary workload inside a UML
# instance. We do _not_ extend 'common', which is the template for a normal HCP
# workload running in the container, because we aren't that. (We're actually
# redirecting the intended "normal HCP service" into a VM context.) To wit;
# - the fqdn-bus and usecase mounts aren't for what's in the container, they're
#   placed at paths that will mount into the VM.
# - no 'hostname' property, the workload inside the UML instance should
#   determine what hostname(s) it advertises.
    uml_runner:
        image: ${HCP_IMAGE_caboodle}
        init: true
        cap_add:
          - SYS_ADMIN
        environment:
          - HCP_CONFIG_FILE=/hostfs/usecase/uml_runner.json
        volumes:
          - fqdn:/hostfs/fqdn-bus:rw
          - ${HCP_TOP}/usecase:/hostfs/usecase:ro
          - ${HCP_OUT}/uml/converted/caboodle.ext4:/rootfs.ext4:ro
        tmpfs:
          - /dev/shm:exec
        networks:
          - hcpnetwork

    uml1:
        extends: common
        image: hcp_uml_run:devel
        hostname: uml1.hcphacking.xyz
        cap_add:
          - SYS_ADMIN
        environment:
          - HCP_CONFIG_FILE=/usecase/uml1.json
        volumes:
          - ${HCP_OUT}/uml/uml_bootstrapper.ext4:/rootfs.ext4:ro
        tmpfs:
          - /dev/shm:exec
        networks:
          - hcpnetwork

    qemu_runner:
        image: ${HCP_IMAGE_qemu}
        init: true
        cap_add:
          - SYS_ADMIN
        environment:
          - HCP_CONFIG_FILE=/hostfs/usecase/qemu_runner.json
        volumes:
          - fqdn:/hostfs/fqdn-bus:rw
          - attestdb:/hostfs/attestdb:rw
          - ${HCP_TOP}/usecase:/hostfs/usecase:ro
          - ${HCP_OUT}/apps/qemu_caboodle_img:/qemu_caboodle_img:ro
        tmpfs:
          - /dev/shm:exec
        networks:
          - hcpnetwork

    # Use this variant if you want QEMU to launch a VGA window, and if
    # HCP_APP_QEMU_XFORWARD is enabled in settings.mk, and if you an X
    # environment to forward!)
    qemu_runner_x11:
        extends: qemu_runner
        environment:
          - XAUTHORITY=/xauth
          - DISPLAY=${DISPLAY}
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ${HCP_OUT}/docker-compose.xauth:/xauth:ro
