# Using this version string helps with some older docker-compose versions that
# we regularly encounter.
version: "3.0"

# NB: use of this file by 'docker-compose' depends on configuration settings
# found in 'defaults.env'. This means you must either;
#
# (a) pass '--env-file=defaults.env' to docker-compose,
# (b) source defaults.env into the environment that will run docker-compose, or
# (c) create a symlink from '.env' -> 'defaults.env' so that docker-compose
#     picks up them up automatically.
#
# We contemplated two alternatives to these requirements;
#
# 1. rename the default settings file to '.env', so that docker-compose would
#    pick it up automatically. Rejected: that would hide the one file that we
#    most want first-time users to find.
# 2. put an '.env' -> 'defaults.env' symlink into version control, so that
#    suggestion (c) is pre-arranged. Rejected: we want the HCP code to pose as
#    few portability and filesystem-specific challenges going forward, and
#    committing symlinks into version control seemed a backwards step in this
#    regard.
#
# PLEASE READ 'defaults.env'!! It not only provides settings, it also provides
# a lot of explanatory content. (Which is the reason this comment is the last
# one you'll see in this file.)

volumes:
    enrolldb:
    attestdb:
    swtpm:
    tpmsocket:

networks:
    hcpnetwork:

services:

    enrollsvc_mgmt:
        image: ${HCP_IMAGE_ENROLLSVC}
        command: /hcp/enrollsvc/run_mgmt.sh
        volumes:
          - enrolldb:${HCP_ENROLLSVC_STATE_PREFIX}:rw
          - ${HCP_CRED_ENROLL_SIGNATURE}:${HCP_ENROLLSVC_SIGNER}:ro
          - ${HCP_CRED_ENROLL_X509_CA}:${HCP_ENROLLSVC_GENCERT}:ro
        networks:
          - hcpnetwork
        environment:
          - HCP_ENROLLSVC_STATE_PREFIX=${HCP_ENROLLSVC_STATE_PREFIX}
          - HCP_ENROLLSVC_SIGNER=${HCP_ENROLLSVC_SIGNER}
          - HCP_ENROLLSVC_GENCERT=${HCP_ENROLLSVC_GENCERT}
          - HCP_ENROLLSVC_REALM=${HCP_ENROLLSVC_REALM}
        healthcheck:
            test: curl -f -G http://localhost:5000/ || exit 1
            timeout: 1s
            interval: 2s

    enrollsvc_repl:
        image: ${HCP_IMAGE_ENROLLSVC}
        command: /hcp/enrollsvc/run_repl.sh
        volumes:
          - enrolldb:${HCP_ENROLLSVC_STATE_PREFIX}:ro
        networks:
          - hcpnetwork
        environment:
          - HCP_ENROLLSVC_STATE_PREFIX=${HCP_ENROLLSVC_STATE_PREFIX}
        healthcheck:
            test: git ls-remote --heads git://localhost/enrolldb || exit 1
            timeout: 1s
            interval: 2s

    attestsvc_repl:
        image: ${HCP_IMAGE_ATTESTSVC}
        command: /hcp/attestsvc/run_repl.sh
        volumes:
          - attestdb:${HCP_ATTESTSVC_STATE_PREFIX}:rw
        networks:
          - hcpnetwork
        environment:
          - HCP_ATTESTSVC_STATE_PREFIX=${HCP_ATTESTSVC_STATE_PREFIX}
          - HCP_ATTESTSVC_REMOTE_REPO=${HCP_ATTESTSVC_REMOTE_REPO}
          - HCP_ATTESTSVC_UPDATE_TIMER=${HCP_ATTESTSVC_UPDATE_TIMER}
        healthcheck:
            test: test -f /attestdb/initialized && test ! -f /attestdb/transient-failure
            timeout: 1s
            interval: 2s

    attestsvc_hcp:
        image: ${HCP_IMAGE_ATTESTSVC}
        command: /hcp/attestsvc/run_hcp.sh
        volumes:
          - attestdb:${HCP_ATTESTSVC_STATE_PREFIX}:ro
        networks:
          - hcpnetwork
        environment:
          - HCP_ATTESTSVC_STATE_PREFIX=${HCP_ATTESTSVC_STATE_PREFIX}
        healthcheck:
            test: curl -f -G http://localhost:8080/ || exit 1
            timeout: 1s
            interval: 2s

    swtpmsvc:
        image: ${HCP_IMAGE_SWTPMSVC}
        command: /hcp/swtpmsvc/run_swtpm.sh
        volumes:
          - swtpm:${HCP_SWTPMSVC_STATE_PREFIX}
          - tpmsocket:/tpmsocket
        networks:
          - hcpnetwork
        environment:
          - HCP_SWTPMSVC_STATE_PREFIX=${HCP_SWTPMSVC_STATE_PREFIX}
          - HCP_SWTPMSVC_ENROLL_HOSTNAME=${HCP_SWTPMSVC_ENROLL_HOSTNAME}
          - HCP_SOCKET=/tpmsocket/tpm
          - HCP_SWTPMSVC_ENROLL_API=${HCP_SWTPMSVC_ENROLL_API}
          - HCP_SWTPMSVC_NO_ENROLL=${HCP_SWTPMSVC_NO_ENROLL}
        healthcheck:
            test: /hcp/swtpmsvc/healthcheck.sh
            timeout: 1s
            interval: 2s
    swtpmsvc_setup:
        extends: swtpmsvc
        command: /hcp/swtpmsvc/setup_swtpm.sh
    swtpmsvc_setup_no_enroll:
        extends: swtpmsvc_setup
        environment:
          - HCP_SWTPMSVC_NO_ENROLL=1

    client:
        image: ${HCP_IMAGE_CLIENT}
        command: /hcp/client/run_client.sh
        volumes:
          - tpmsocket:/tpmsocket
          - ${HCP_CRED_ENROLL_VERIFIER}:${HCP_CLIENT_VERIFIER}:ro
        networks:
          - hcpnetwork
        environment:
          - HCP_CLIENT_ATTEST_URL=http://attestsvc_hcp:8080
          - HCP_CLIENT_TPM2TOOLS_TCTI=swtpm:path=/tpmsocket/tpm
          - HCP_CLIENT_VERIFIER=${HCP_CLIENT_VERIFIER}
