$(eval $(call app_add,caboodle,include,644,common.sh))
$(eval $(call app_finalize,caboodle))
$(eval $(call app_image,caboodle,common enrollsvc attestsvc swtpmsvc kdc tools caboodle,install safeboot))
