include $(HCP_SRC)/ext/Makefile.api
# External (submodule) code-bases to be packaged
include $(HCP_SRC)/ext/tpmware.Makefile
include $(HCP_SRC)/ext/heimdal.Makefile
include $(HCP_SRC)/ext/safeboot.Makefile
