# vim: set expandtab shiftwidth=4 softtabstop=4:
# Using this version string helps with some older docker-compose versions that
# we regularly encounter. It also ensures the 'extend' feature works.
version: "2.4"

volumes:
    fqdn:
    enrolldb:
    attestdb:
    kdc_primary:
    kdc_secondary:
    sherver:
    tpm_aclient:
    tpmsocket_aclient:
    tpm_kdc_primary:
    tpmsocket_kdc_primary:
    tpm_kdc_secondary:
    tpmsocket_kdc_secondary:
    tpm_workstation1:
    tpmsocket_workstation1:
    tpm_sherver:
    tpmsocket_sherver:
    emgmt_qemu:
    bigbrother_tpm:
    target_tpm:

networks:
    emgmt_private:
        internal: true
    kdc_primary_private:
        internal: true
    kdc_secondary_private:
        internal: true
    hcpnetwork:
        # internal: true

services:

    common:
        image: ${HCP_IMAGE_caboodle}
        init: true
        volumes:
          - fqdn:/fqdn-bus:rw
          - ${TOP}/usecase:/usecase:ro
          - ${TOP}/src/hcp:/hcp:ro
        environment:
          - HCP_LAUNCHER_TGTS=${HCP_LAUNCHER_TGTS:-}
          - HCP_NOTRACEFILE=1
          - VERBOSE=${VERBOSE:-0}

    uml_runner:
        extends: common
        image: ${HCP_IMAGE_uml_caboodle}
        cap_add:
          - SYS_ADMIN
        volumes:
          - ${HCP_OUT}/apps/uml_caboodle.ext4:/uml_caboodle.ext4:ro
        tmpfs:
          - /dev/shm:exec

    qemu_runner:
        extends: common
        image: ${HCP_IMAGE_qemu_caboodle}
        cap_add:
          - SYS_ADMIN
        volumes:
          - ${HCP_OUT}/apps/qemu_caboodle_img:/qemu_caboodle_img:ro
        devices:
          - /dev/kvm:/dev/kvm
        tmpfs:
          - /dev/shm:exec

    # Use this variant if (a) you want QEMU to launch a VGA window, (b)
    # HCP_APP_QEMU_XFORWARD is enabled in settings.mk, and (c) if you have an X
    # environment ("make" will populate output/docker-compose.xauth).
    qemu_runner_x11:
        extends: qemu_runner
        environment:
          - XAUTHORITY=/xauth
          - DISPLAY=${DISPLAY}
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ${HCP_OUT}/docker-compose.xauth:/xauth:ro

# Enrollment svc, mgmt interface
    emgmt:
        extends: common
        #extends: qemu_runner
        hostname: emgmt.hcphacking.xyz
        networks:
          - hcpnetwork
          - emgmt_private
        volumes:
        #  - emgmt_qemu:/qemu_state
          - enrolldb:/enrolldb:rw
          - ${HCP_TESTCREDS_ENROLLSIGNER}:/enrollsigner:ro
          - ${HCP_TESTCREDS_ENROLLCERTISSUER}:/enrollcertissuer:ro
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - ${HCP_TESTCREDS_ENROLLSERVER}:/enrollserver:ro
          - ${TOP}/vendors:/vendors:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/emgmt.json
          #- HCP_CONFIG_FILE=/usecase/emgmt_qemu.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck
            timeout: 30s
            interval: 60s

# Enrollment svc, QEMU alternative
    emgmt_qemu:
        extends: qemu_runner_x11
        hostname: emgmt.hcphacking.xyz
        networks:
          - hcpnetwork
          - emgmt_private
        volumes:
          - emgmt_qemu:/qemu_state
          - enrolldb:/enrolldb:rw
          - ${HCP_TESTCREDS_ENROLLSIGNER}:/enrollsigner:ro
          - ${HCP_TESTCREDS_ENROLLCERTISSUER}:/enrollcertissuer:ro
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - ${HCP_TESTCREDS_ENROLLSERVER}:/enrollserver:ro
          - ${TOP}/vendors:/vendors:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/emgmt_qemu.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck
            timeout: 30s
            interval: 60s

# Enrollment svc, policy engine
    emgmt_pol:
        extends: common
        #extends: qemu_runner
        #extends: uml_runner
        hostname: emgmt_pol.hcphacking.xyz
        networks:
          - emgmt_private
        environment:
          - HCP_CONFIG_FILE=/usecase/emgmt_pol.json
          #- HCP_CONFIG_FILE=/usecase/emgmt_pol_qemu.json
          #- HCP_CONFIG_FILE=/usecase/emgmt_pol_uml.json
        healthcheck:
            test: /hcp/webapi.py healthcheck
            timeout: 30s
            interval: 60s

# Enrollment svc, replication interface
    erepl:
        extends: common
        hostname: erepl.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes: # TODO: mount this at /enrolldb-ro? (For monolith...)
          - enrolldb:/enrolldb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/erepl.json
        healthcheck:
            test: /hcp/enrollsvc/repl_healthcheck.sh
            timeout: 30s
            interval: 60s

# Attestation svc, replication client
    arepl:
        extends: common
        hostname: arepl.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - attestdb:/attestdb:rw
        environment:
          - HCP_CONFIG_FILE=/usecase/arepl.json
        healthcheck:
            test: test -f /attestdb/initialized && ! test -f /attestdb/hcp/transient-failure
            timeout: 30s
            interval: 60s

# Attestation svc, attestation interface
    ahcp:
        extends: common
        hostname: ahcp.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - attestdb:/attestdb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/ahcp.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck
            timeout: 30s
            interval: 60s

# Orchestrator client (create and/or enroll TPMs). You'll typically want to
# pass "-c -e" to this to make it do something.
    orchestrator:
        extends: common
        hostname: orchestrator.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - tpm_aclient:/tpm_aclient
          - tpm_kdc_primary:/tpm_kdc_primary
          - tpm_kdc_secondary:/tpm_kdc_secondary
          - tpm_workstation1:/tpm_workstation1
          - tpm_sherver:/tpm_sherver
          - bigbrother_tpm:/tpm_bigbrother
          - target_tpm:/tpm_target
        environment:
          - HCP_CONFIG_FILE=/usecase/orchestrator.json

# Attestation client
    aclient:
        extends: common
        hostname: aclient.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - tpmsocket_aclient:/tpm_socket_aclient
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/aclient.json
    aclient_tpm:
        extends: common
        hostname: aclient_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_aclient:/tpm_aclient
          - tpmsocket_aclient:/tpm_socket_aclient
        environment:
          - HCP_CONFIG_FILE=/usecase/aclient_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck
            timeout: 30s
            interval: 60s

# Kerberos Domain Controller - Primary
    kdc_primary:
        extends: common
        hostname: kdc_primary.hcphacking.xyz
        volumes:
          - kdc_primary:/kdc_primary
          - tpmsocket_kdc_primary:/tpm_socket_kdc_primary
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        networks:
          - hcpnetwork
          - kdc_primary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_primary.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck && /hcp/kdcsvc/realm_healthcheck.py
            timeout: 30s
            interval: 60s
    kdc_primary_tpm:
        extends: common
        hostname: kdc_primary_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_kdc_primary:/tpm_kdc_primary
          - tpmsocket_kdc_primary:/tpm_socket_kdc_primary
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_primary_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck
            timeout: 30s
            interval: 60s
    kdc_primary_pol:
        extends: common
        hostname: kdc_primary_pol.hcphacking.xyz
        networks:
          - kdc_primary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_primary_pol.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck
            timeout: 30s
            interval: 60s

# Kerberos Domain Controller - Secondary
    kdc_secondary:
        extends: common
        hostname: kdc_secondary.hcphacking.xyz
        volumes:
          - kdc_secondary:/kdc_secondary
          - tpmsocket_kdc_secondary:/tpm_socket_kdc_secondary
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        networks:
          - hcpnetwork
          - kdc_secondary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_secondary.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck && /hcp/kdcsvc/realm_healthcheck.py
            timeout: 30s
            interval: 60s
    kdc_secondary_tpm:
        extends: common
        hostname: kdc_secondary_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_kdc_secondary:/tpm_kdc_secondary
          - tpmsocket_kdc_secondary:/tpm_socket_kdc_secondary
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_secondary_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck
            timeout: 30s
            interval: 60s
    kdc_secondary_pol:
        extends: common
        hostname: kdc_secondary_pol.hcphacking.xyz
        networks:
          - kdc_secondary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_secondary_pol.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck
            timeout: 30s
            interval: 60s

# SSH host
    sherver:
        extends: common
        hostname: sherver.hcphacking.xyz
        volumes:
          - sherver:/sherver:rw
          - tpmsocket_sherver:/tpm_socket_sherver
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        networks:
          - hcpnetwork
        environment:
          - HCP_CONFIG_FILE=/usecase/sherver.json
        healthcheck:
            test: /hcp/sshd.py --healthcheck
            timeout: 30s
            interval: 60s
    sherver_tpm:
        extends: common
        hostname: sherver_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_sherver:/tpm_sherver
          - tpmsocket_sherver:/tpm_socket_sherver
        environment:
          - HCP_CONFIG_FILE=/usecase/sherver_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck
            timeout: 30s
            interval: 60s

# 'workstation1' represents an architypal machine that is bootstrapped by the
# HCP infrastructure. It gets provisioned with host and user credentials, and
# can be used to interact with Kerberos and SSH services on the network in a
# SSO manner. It is used (non-interactively) for this purpose by the
# 'services_basic' test case.
    workstation1:
        extends: common
        hostname: workstation1.hcphacking.xyz
        environment:
          - HCP_CONFIG_FILE=/usecase/workstation1.json
          - HCP_NOTRACEFILE=1
        volumes:
          - ${TOP}/vendors:/vendors:ro
          - tpmsocket_workstation1:/tpm_socket_workstation1
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
        networks:
          - hcpnetwork
        healthcheck:
            test: /hcp/caboodle/networked_healthcheck.sh
            timeout: 30s
            interval: 60s
    workstation1_tpm:
        extends: common
        hostname: workstation1_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_workstation1:/tpm_workstation1
          - tpmsocket_workstation1:/tpm_socket_workstation1
        environment:
          - HCP_CONFIG_FILE=/usecase/workstation1_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck
            timeout: 30s
            interval: 60s

    bigbrother:
        extends: common
        hostname: bigbrother.hcphacking.xyz
        volumes:
          - bigbrother_tpm:/tpm_bigbrother
        networks:
          - hcpnetwork
        environment:
          - HCP_CONFIG_FILE=/usecase/bigbrother.json

    target:
        extends: common
        hostname: target.hcphacking.xyz
        volumes:
          - target_tpm:/tpm_target
        networks:
          - hcpnetwork
        environment:
          - HCP_CONFIG_FILE=/usecase/target.json

# 'monolith' exists to run all of the workloads that the targets above run in
# separate containers, but running them co-tenant within this single container
# rather than broken out. (HCP implements a "docker-compose" replacement called
# "monolith.py" that can be hooked into test scripts, and that causes it to
# invoke launcher.py directly rather than doing so via docker-compose commands
# into separate containers.)
    monolith:
        extends: common
        hostname: monolith.hcphacking.xyz
        environment:
          - HCP_IN_MONOLITH=1
          - HCP_CONFIG_FILE=/usecase/monolith.json
          - HCP_NOTRACEFILE=1
        volumes:
          - ${TOP}/vendors:/vendors:ro
          - ${HCP_TESTCREDS_ENROLLSIGNER}:/enrollsigner:ro
          - ${HCP_TESTCREDS_ENROLLCERTISSUER}:/enrollcertissuer:ro
          - ${HCP_TESTCREDS_ENROLLCERTCHECKER}:/enrollcertchecker:ro
          - ${HCP_TESTCREDS_ENROLLCLIENT}:/enrollclient:ro
          - ${HCP_TESTCREDS_ENROLLSERVER}:/enrollserver:ro
          - ${HCP_TESTCREDS_ENROLLVERIFIER}:/enrollverifier:ro
          - ${TOP}/tests:/tests:ro
        networks:
          - hcpnetwork
        healthcheck:
            test: /bin/true
            timeout: 30s
            interval: 60s
