#!/bin/bash

# In producing a distributable krb5.conf, some assumptions are made.
# Ultimately, more controls should be added (passed from the client and/or
# configured on the enrollsvc) to avoid making these assumptions. Eg. "kdc1".

cd "$1"

cat > krb5.conf << EOF
[libdefaults]
	default_realm = $ENROLL_REALM
[realms]
	$ENROLL_REALM = {
		kdc = kdc1.$ENROLL_DOMAIN
		kpasswd_server = kdc1.$ENROLL_DOMAIN
		admin_server = kdc1.$ENROLL_DOMAIN
	}
EOF

echo "public krb5.conf"
