#!/bin/bash

source /hcp/sshsvc/common.sh

if [[ ! -f $HCP_SSHSVC_GLOBAL_INIT ]]; then
	echo "Error, setup_local.sh being run before setup_global.sh" >&2
	exit 1
fi

if [[ -f "$HCP_SSHSVC_LOCAL_INIT" ]]; then
	echo "Error, setup_local.sh being run but already initialized" >&2
	exit 1
fi

echo "Initializing (rootfs-local) sshsvc state"

# sshd expects this directory to exist
mkdir -p /run/sshd
chmod 755 /run/sshd

# and we want sshd to use these settings;
if [[ ! -f /etc/ssh/sshd_config.d/hcp_ssh_svc.conf ]]; then
	cat > /etc/ssh/sshd_config.d/hcp_ssh_svc.conf <<EOF
# Auto-generated by run_sshsvc.sh
# We need to enable GSSAPI authn to use Kerberos
GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
PasswordAuthentication no
EOF
fi

# Done!
touch "$HCP_SSHSVC_LOCAL_INIT"
